### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by shspage** [Ushio/Catenaly#1]
こんにちは。
カテナリー曲線について調べていて、こちらの素晴らしいツールに辿り着きました。
Qiitaの記事も大変興味深く楽しく拝読しました。

現在、namespace catenary の部分をそのまま使用して、
Adobe Illustratorのプラグインを作成し公開したいと考えているのですが、
こちらのコードのライセンスはどのようなものになりますでしょうか。
自分で書いたコード部分については、そのライセンスに準ずるものか、
またはMITを考えています。
もしライセンスに関する記載を見逃していたようでしたらお知らせ頂けると
助かります。

煩わしいお願いをして大変恐縮ですが、よろしくお願いいたします。

**Comment by Ushio** [comment]
@shspage さん
こんにちは
ライセンスとかは特に何も考えていなかっただけでした。とりあえず緩いので良いかと思いましたので、The zlib/libpng Licenseを入れておきました、不都合あれば教えてください。基本的に自由に使っていただいて大丈夫です。

**Comment by shspage** [comment]
早々のご回答と、使用しやすいライセンス記載の追加ありがとうございます。
プラグインは追ってforkの形で公開したいと思います。
不都合な点がありましたらお知らせください。
